language: python
python:
  - "3.7"

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="P10_deploy.settings.production"

services:
  - postgresql

script:
  - ./manage.py test --settings=settings.__init__
