language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="disquP10_deployaire_project.settings"

services:
  - postgresql

script:
  - ./manage.py test