dist: xenial
language: python
python:
  - "3.7"

before_script:
  - pip install -r requirements.txt
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz"
  - tar xfz geckodriver-v0.27.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - 'export DISPLAY=:99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3

env: DJANGO_SETTINGS_MODULE="P10_deploy.settings.production"

services:
  - postgresql
  - xvfb

script:
  - ./manage.py test --settings=settings.travis
